// packages/react/src/App.tsx
import './App.css'
import BaMaoCodeMirror from '@/components/CodeMirror'
import { useState } from 'react'

function App() {
  const [value, setValue] = useState(
    `function a () { \n console.log('123')console.log('123')console.log('123')console.log('123')console.log('123')console.log('123')console.log('123')console.log('123')console.log('123')console.log('123')console.log('123')console.log('123')console.log('123')console.log('123')console.log('123')\n}`
  )
  const [options, setOptions] = useState({
    height: '600px',
    lineWrapping: false,
  })
  setTimeout(() => {
    setValue(
      `function a () { \n console.log('456')console.log('456')console.log('456')console.log('456')console.log('456')console.log('456')console.log('456')console.log('456')console.log('456')console.log('456')console.log('456')console.log('456')console.log('456')\n}`
    )
    setOptions({
      height: '300px',
      lineWrapping: true,
    })
  }, 6000)
  return (
    <div className="p-4">
      <BaMaoCodeMirror value={value} options={options} />
    </div>
  )
}

export default App

// packages/vue/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import BamaoCodeMirror from './components/CodeMirror/index.vue'
const value = ref(`const { title = '',
  hideHeader = false,
  disabled = false,
  lineWrapping = true,
  width = '100%',
  height = '100%',
  classNames = [] } = options`)
const options = ref({})

onMounted(() => {
  setTimeout(() => {
    value.value = `const { title = '',
  hideHeader = false,
  disabled = false,
  lineWrapping = true,
  width = '100%',
  height = '100%',
  classNames = [] } = options || {}`
    options.value = {
      title: '测试标题',
      hideHeader: true,
      disabled: true,
      langMode: 'markdown',
    }
  }, 1000)
})
</script>

<template>
  <div class="p-2">
    <BamaoCodeMirror v-model="value" :options="options" />
  </div>
</template>
